//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitcoinTransactionManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.ExecutionsAccount = new HashSet<ExecutionsAccount>();
            this.FundsBalance = new HashSet<FundsBalance>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid ExchangeId { get; set; }
        public string Name { get; set; }
        public string APIKey { get; set; }
        public string Secret { get; set; }
        public string CreateID { get; set; }
        public Nullable<System.DateTime> Createdt { get; set; }
        public string UpdateID { get; set; }
        public Nullable<System.DateTime> Updatedt { get; set; }
        public string DisableID { get; set; }
        public Nullable<System.DateTime> Disabledt { get; set; }
        public int Status { get; set; }
    
        public virtual Exchange Exchange { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExecutionsAccount> ExecutionsAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FundsBalance> FundsBalance { get; set; }
    }
}
