//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitcoinTransactionManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BitcoinTransactionEntities : DbContext
    {
        public BitcoinTransactionEntities()
            : base("name=BitcoinTransactionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Currency> Currency { get; set; }
        public virtual DbSet<Exchange> Exchange { get; set; }
        public virtual DbSet<ExchangeCurrency> ExchangeCurrency { get; set; }
        public virtual DbSet<ExchangeTypes> ExchangeTypes { get; set; }
        public virtual DbSet<Executions> Executions { get; set; }
        public virtual DbSet<ExecutionsAccount> ExecutionsAccount { get; set; }
        public virtual DbSet<FundsBalance> FundsBalance { get; set; }
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<TransactionConfirmed> TransactionConfirmed { get; set; }
        public virtual DbSet<TransactionRecords> TransactionRecords { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
