//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitcoinTransactionManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangeCurrency
    {
        public System.Guid ExchangeId { get; set; }
        public string CurrencyVal { get; set; }
        public string CreateID { get; set; }
        public Nullable<System.DateTime> Createdt { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Exchange Exchange { get; set; }
    }
}
