//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitcoinTransactionManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionRecords
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransactionRecords()
        {
            this.TransactionConfirmed = new HashSet<TransactionConfirmed>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid ExecutionsId { get; set; }
        public System.DateTime Createdt { get; set; }
        public decimal Quantity { get; set; }
        public decimal Profit { get; set; }
        public string ExchangeType { get; set; }
    
        public virtual Executions Executions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionConfirmed> TransactionConfirmed { get; set; }
    }
}
