//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitcoinTransactionManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionConfirmed
    {
        public System.Guid id { get; set; }
        public System.Guid TransactionRecordsId { get; set; }
        public System.Guid AccountId { get; set; }
        public decimal Prices { get; set; }
        public decimal ProcessingPrices { get; set; }
        public decimal ProcessingFee { get; set; }
        public System.DateTime Createdt { get; set; }
        public int TransactionType { get; set; }
        public int Status { get; set; }
        public string Message { get; set; }
    
        public virtual TransactionRecords TransactionRecords { get; set; }
    }
}
